-- AlterTable
ALTER TABLE `soptemplate` MODIFY `category` ENUM('VIDEO_EDITING', 'CLIENT_VIDEO_RECORDING', 'GRAPHIC_DESIGN', 'ADS_MANAGEMENT', 'SHOOT', 'CONTENT_WRITING', 'STRATEGY', 'REPORTING', 'OTHER') NOT NULL;

-- AlterTable
ALTER TABLE `task` MODIFY `category` ENUM('VIDEO_EDITING', 'CLIENT_VIDEO_RECORDING', 'GRAPHIC_DESIGN', 'ADS_MANAGEMENT', 'SHOOT', 'CONTENT_WRITING', 'STRATEGY', 'REPORTING', 'OTHER') NOT NULL;
